import type {Metadata} from "next";
import "./globals.css";
import FooterLayout from "@/ui/layouts/FooterLayout";
import NavBarLayout from "@/ui/layouts/NavBarLayout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">


        <body>
        <NavBarLayout/>
        {children}
        <footer>
            <FooterLayout/>
        </footer>
        </body>

        </html>
    );
}
